DATA CLEANING OF TRAINING SET

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import sklearn

In [2]:
df=pd.read_csv('training_set_features.csv',index_col=0)

In [3]:
df.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
respondent_id,,,,,,,,,,,,,,,,,,,,,
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [4]:
df.shape

(26707, 35)

In [5]:
df.isnull().sum()

xyz_concern                       92
xyz_knowledge                    116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_xyz_vacc_effective       391
opinion_xyz_risk                 388
opinion_xyz_sick_from_vacc       395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
rent_or_own                     2042
employment_status               1463
hhs_geo_region                     0
census_msa                         0
household_adults                 249
household_children               249
employment_industry            13330
employment_occupation          13470
dtype: int64

In [6]:
df['xyz_concern']=df['xyz_concern'].fillna(2.0)
df['xyz_knowledge']=df['xyz_knowledge'].fillna(1.0)
df['behavioral_antiviral_meds'].value_counts()
df['behavioral_antiviral_meds']=df['behavioral_antiviral_meds'].fillna(0.0)
df['behavioral_avoidance']=df['behavioral_avoidance'].fillna(df['behavioral_avoidance'].mode()[0])
df['behavioral_face_mask']=df['behavioral_face_mask'].fillna(df['behavioral_face_mask'].mode()[0])
df['behavioral_wash_hands']=df['behavioral_wash_hands'].fillna(df['behavioral_wash_hands'].mode()[0])
df['behavioral_large_gatherings']=df['behavioral_large_gatherings'].fillna(df['behavioral_large_gatherings'].mode()[0])
df['behavioral_outside_home']= df['behavioral_outside_home'].fillna(df['behavioral_outside_home'].mode()[0])
df['behavioral_touch_face']= df['behavioral_touch_face'].fillna(df['behavioral_touch_face'].mode()[0])
df['doctor_recc_xyz'].value_counts()
#df.dropna(subset=['education','marital_status','rent_or_own','income_poverty','employment_industry','employment_occupation'],inplace=True)
df['employment_status']=df['employment_status'].fillna('Employed')
df['household_adults']=df['household_adults'].fillna(1.0)
df['household_children']=df['household_children'].fillna(0.0)
df['child_under_6_months']=df['child_under_6_months'].fillna(0.0)
df['health_worker']= df['health_worker'].fillna(df['health_worker'].mode()[0])
df['opinion_seas_sick_from_vacc']=df['opinion_seas_sick_from_vacc'].fillna(1.0)
df['opinion_xyz_sick_from_vacc']=df['opinion_xyz_sick_from_vacc'].fillna(2.0)
df['opinion_seas_risk']=df['opinion_seas_risk'].fillna(2.0)
df['opinion_xyz_risk']=df['opinion_xyz_risk'].fillna(2.0)
df['opinion_seas_vacc_effective']=df['opinion_seas_vacc_effective'].fillna(4.0)
df['opinion_xyz_vacc_effective']=df['opinion_xyz_vacc_effective'].fillna(4.0)
df['doctor_recc_seasonal']=df['doctor_recc_seasonal'].fillna(0.0)
df['doctor_recc_xyz']=df['doctor_recc_xyz'].fillna(0.0)
df['health_insurance']=-df['health_insurance'].fillna(1.0)
df['chronic_med_condition']=df['chronic_med_condition'].fillna(0.0)
df=df.drop(['employment_occupation','employment_industry','census_msa','hhs_geo_region','employment_status','rent_or_own','marital_status','race','education'],axis=1)
df=pd.get_dummies(df, columns=['sex', 'age_group','income_poverty'])
df.replace({True: 1.0, False:0.0}, inplace=True)
#df['respondent_id']=df['respondent_id'].astype(float)

C:\Users\hp\AppData\Local\Temp\ipykernel_11104\1758845231.py:30: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({True: 1.0, False:0.0}, inplace=True)

DATA CLEANING OF TEST SET

In [7]:
dt=pd.read_csv('test_set_features.csv',index_col=0)

In [8]:
dt.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
respondent_id,,,,,,,,,,,,,,,,,,,,,
26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,...,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,NaN,NaN
26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird

In [9]:
dt['xyz_concern']=dt['xyz_concern'].fillna(2.0)
dt['xyz_knowledge']=dt['xyz_knowledge'].fillna(1.0)
dt['behavioral_antiviral_meds'].value_counts()
dt['behavioral_antiviral_meds']=dt['behavioral_antiviral_meds'].fillna(0.0)
dt['behavioral_avoidance']=dt['behavioral_avoidance'].fillna(dt['behavioral_avoidance'].mode()[0])
dt['behavioral_face_mask']=dt['behavioral_face_mask'].fillna(dt['behavioral_face_mask'].mode()[0])
dt['behavioral_wash_hands']=dt['behavioral_wash_hands'].fillna(dt['behavioral_wash_hands'].mode()[0])
dt['behavioral_large_gatherings']=dt['behavioral_large_gatherings'].fillna(dt['behavioral_large_gatherings'].mode()[0])
dt['behavioral_outside_home']= dt['behavioral_outside_home'].fillna(dt['behavioral_outside_home'].mode()[0])
dt['behavioral_touch_face']= dt['behavioral_touch_face'].fillna(dt['behavioral_touch_face'].mode()[0])
dt['doctor_recc_xyz'].value_counts()
#dt.dropna(subset=['education','marital_status','rent_or_own','income_poverty','employment_industry','employment_occupation'],inplace=True)
dt['employment_status']=dt['employment_status'].fillna('Employed')
dt['household_adults']=dt['household_adults'].fillna(1.0)
dt['household_children']=dt['household_children'].fillna(0.0)
dt['child_under_6_months']=dt['child_under_6_months'].fillna(0.0)
dt['health_worker']= dt['health_worker'].fillna(dt['health_worker'].mode()[0])
dt['opinion_seas_sick_from_vacc']=dt['opinion_seas_sick_from_vacc'].fillna(1.0)
dt['opinion_xyz_sick_from_vacc']=dt['opinion_xyz_sick_from_vacc'].fillna(2.0)
dt['opinion_seas_risk']=dt['opinion_seas_risk'].fillna(2.0)
dt['opinion_xyz_risk']=dt['opinion_xyz_risk'].fillna(2.0)
dt['opinion_seas_vacc_effective']=dt['opinion_seas_vacc_effective'].fillna(4.0)
dt['opinion_xyz_vacc_effective']=dt['opinion_xyz_vacc_effective'].fillna(4.0)
dt['doctor_recc_seasonal']=dt['doctor_recc_seasonal'].fillna(0.0)
dt['doctor_recc_xyz']=dt['doctor_recc_xyz'].fillna(0.0)
dt['health_insurance']=-dt['health_insurance'].fillna(1.0)
dt['chronic_med_condition']=dt['chronic_med_condition'].fillna(0.0)
dt=dt.drop(['employment_occupation','employment_industry','census_msa','hhs_geo_region','employment_status','rent_or_own','marital_status','race','education'],axis=1)
dt=pd.get_dummies(dt, columns=['sex', 'age_group','income_poverty'])
dt.replace({True: 1.0, False:0.0}, inplace=True)
#dt['respondent_id']=dt['respondent_id'].astype(float)

C:\Users\hp\AppData\Local\Temp\ipykernel_11104\1503312493.py:30: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dt.replace({True: 1.0, False:0.0}, inplace=True)

In [10]:
dt.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,sex_Female,sex_Male,age_group_18 - 34 Years,age_group_35 - 44 Years,age_group_45 - 54 Years,age_group_55 - 64 Years,age_group_65+ Years,"income_poverty_<= $75,000, Above Poverty","income_poverty_> $75,000",income_poverty_Below Poverty
respondent_id,,,,,,,,,,,,,,,,,,,,,
26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [11]:
dt.index

Index([26707, 26708, 26709, 26710, 26711, 26712, 26713, 26714, 26715, 26716,
       ...
       53405, 53406, 53407, 53408, 53409, 53410, 53411, 53412, 53413, 53414],
      dtype='int64', name='respondent_id', length=26708)

PERFORMING LOGISTIC REGRESSION MODEL ON GIVEN DATA FOR SEASONAL VACCINE

In [12]:
dp=pd.read_csv('training_set_labels.csv')

In [13]:
ds=dp.drop(['respondent_id','xyz_vaccine'],axis=1)

In [14]:
ds.head()

   seasonal_vaccine
0                 0
1                 1
2                 0
3                 1
4                 0

In [15]:
X_tran=df
y_tran=ds
X_test=dt

In [33]:
from sklearn.model_selection import train_test_split
#X_tran, X_test, y_tran, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(X_tran, y_tran)
y_stest=model1.predict(X_test)
pred_prob1 = model1.predict_proba(X_test)
at=pd.DataFrame(y_stest)
seasonal=pd.DataFrame(pred_prob1)
seasonal.head()

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

          0         1
0  0.904125  0.095875
1  0.953196  0.046804
2  0.562510  0.437490
3  0.530938  0.469062
4  0.761669  0.238331

PERFORMING LOGISTIC REGRESSION MODEL ON GIVEN DATA FOR XYZ VACCINE

In [34]:
dx=dp.drop(['respondent_id','seasonal_vaccine'],axis=1)

In [35]:
dx.head()

   xyz_vaccine
0            0
1            0
2            0
3            0
4            0

In [36]:
X_tran=df
y_tran=dx
X_test=dt

In [37]:
from sklearn.model_selection import train_test_split
#X_tran, X_test, y_tran, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(X_tran, y_tran)
y_xtest=model1.predict(X_test)
pred_prob2 = model1.predict_proba(X_test)
at=pd.DataFrame(y_xtest)
xyz=pd.DataFrame(pred_prob2)
xyz.head()

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

          0         1
0  0.904125  0.095875
1  0.953196  0.046804
2  0.562510  0.437490
3  0.530938  0.469062
4  0.761669  0.238331

COMPUTING ROC AUC SCORE FOR BOTH VACCINES

In [38]:
from sklearn.metrics import roc_curve


fpr1, tpr1, thresh1 = roc_curve(y_stest, pred_prob1[:,1], pos_label=1)
fpr2, tpr2, thresh2 = roc_curve(y_xtest, pred_prob2[:,1], pos_label=1)
random_probs = [0 for i in range(len(y_xtest))]
p_fpr, p_tpr, _ = roc_curve(y_xtest, random_probs, pos_label=1)

In [39]:
from sklearn.metrics import roc_auc_score


auc_score1 = roc_auc_score(y_stest, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_xtest, pred_prob2[:,1])

print(auc_score1, auc_score2)

1.0 1.0

CREATING A DATAFRAME WITH FINAL PREDICTED PROBABILITIES

In [41]:
submission=pd.DataFrame(columns=['respondent_id','xyz_vaccine','seasonal_vaccine'])

In [42]:
submission['respondent_id']=dt.index
submission['xyz_vaccine']=xyz[1]
submission['seasonal_vaccine']=seasonal[1]

In [43]:
submission.head()

   respondent_id  xyz_vaccine  seasonal_vaccine
0          26707     0.095875          0.095875
1          26708     0.046804          0.046804
2          26709     0.437490          0.437490
3          26710     0.469062          0.469062
4          26711     0.238331          0.238331

In [44]:
submission.to_csv('submission.csv')